/**
 * Purpose:
 * - build the YAML content for a generated Obsidian Bases (.base) file.
 *
 * Responsibilities:
 * - wires up table views over the configured project folders, combining plugin-owned
 *   frontmatter fields (status, priority, waiting-since, reviewed) with the derived
 *   fields mirrored by derived-frontmatter.ts (next-due, next-action, open-tasks), plus
 *   file.folder/file.name columns
 *
 * Dependencies:
 * - settings-utils.ts (TaskManagerSettings) only
 *
 * Side Effects:
 * - none (pure string builder; the I/O — existence check, overwrite confirm, vault
 *   write — lives in main.ts, following the pattern of createProjectFile()/runQuickCapture())
 *
 * Notes:
 * - Empirically, `note["hyphenated-field"]` bracket notation used directly as an `order:`/
 *   `sort:` column reference is accepted by Bases (no schema error, and Bases' own UI
 *   preserves it when round-tripping the file) but does NOT render actual cell values —
 *   every such column showed blank rows in testing, even once a `properties:` displayName
 *   override fixed the header text. So this module routes every hyphenated field through
 *   a `formulas:` entry instead — `note["next-due"]` etc. wrapped in a named formula,
 *   referenced everywhere as `formula.nextDue` — which matches Obsidian's own documented
 *   example verbatim (a `formulas: formatted_price: '...'` entry referenced as
 *   `formula.formatted_price` in `order:` and given a `properties:` displayName), the one
 *   part of this schema with a first-party worked example rather than inference. Formula
 *   names are camelCase specifically so referencing them (`formula.nextDue`) never needs
 *   bracket notation itself. If a view still fails to render or a column is still empty,
 *   that's the next thing to re-verify against https://help.obsidian.md/bases/syntax and
 *   /bases/functions — a bad view only produces a visible error banner scoped to this one
 *   generated file, nothing else in the plugin depends on it parsing correctly.
 */
import { TaskManagerSettings } from "../settings/settings-utils";

type SortDirection = "ASC" | "DESC";

type BaseViewSpec = {
  name: string;
  /** Folder this view is scoped to; omitted from the filter entirely if blank. */
  folder: string;
  /** Additional filter expressions, ANDed with the folder filter. */
  extraFilters: string[];
  /** Column property paths, in display order. */
  order: string[];
  sortProperty: string;
  sortDirection: SortDirection;
};

/** Formula names — camelCase so referencing them as `formula.<name>` never needs bracket notation. */
const NEXT_DUE_FORMULA = "nextDue";
const NEXT_ACTION_FORMULA = "nextAction";
const OPEN_TASKS_FORMULA = "openTasks";
const WAITING_SINCE_FORMULA = "waitingSince";

/** Each formula just unwraps one hyphenated note property — see the module doc comment for why. */
const FORMULAS: Record<string, string> = {
  [NEXT_DUE_FORMULA]: 'note["next-due"]',
  [NEXT_ACTION_FORMULA]: 'note["next-action"]',
  [OPEN_TASKS_FORMULA]: 'note["open-tasks"]',
  [WAITING_SINCE_FORMULA]: 'note["waiting-since"]',
};

const NEXT_DUE = `formula.${NEXT_DUE_FORMULA}`;
const NEXT_ACTION = `formula.${NEXT_ACTION_FORMULA}`;
const OPEN_TASKS = `formula.${OPEN_TASKS_FORMULA}`;
const WAITING_SINCE = `formula.${WAITING_SINCE_FORMULA}`;
const FILE_NAME = "file.name";
const FILE_FOLDER = "file.folder";
const STATUS = "note.status";
const PRIORITY = "note.priority";
const REVIEWED = "note.reviewed";

/** Bare dotted properties (priority, status, reviewed, file.name) already read fine and don't need an entry here. */
const DISPLAY_NAMES: Record<string, string> = {
  [NEXT_DUE]: "Next due",
  [NEXT_ACTION]: "Next action",
  [OPEN_TASKS]: "Open tasks",
  [WAITING_SINCE]: "Waiting since",
};

export function buildTaskBaseFileContent(settings: TaskManagerSettings): string {
  const views = buildViewSpecs(settings);
  const lines: string[] = [
    "# Generated by the Task Manager plugin's \"Create Tasks Summary\" command.",
    "# Re-running the command overwrites this file, discarding any view customizations.",
    "formulas:",
    ...renderFormulas(),
    "views:",
  ];

  for (const view of views) {
    lines.push(...renderView(view));
  }

  lines.push("properties:", ...renderDisplayNames());

  return `${lines.join("\n")}\n`;
}

function renderFormulas(): string[] {
  const lines: string[] = [];
  for (const [name, expression] of Object.entries(FORMULAS)) {
    lines.push(`  ${name}: '${expression.replace(/'/g, "''")}'`);
  }
  return lines;
}

function renderDisplayNames(): string[] {
  const lines: string[] = [];
  for (const [property, displayName] of Object.entries(DISPLAY_NAMES)) {
    lines.push(`  ${property}:`, `    displayName: "${escapeYamlString(displayName)}"`);
  }
  return lines;
}

function buildViewSpecs(settings: TaskManagerSettings): BaseViewSpec[] {
  return [
    {
      name: "Active projects",
      folder: settings.projectsFolder,
      extraFilters: [`${STATUS} == "todo"`],
      order: [FILE_FOLDER, FILE_NAME, PRIORITY, NEXT_DUE, NEXT_ACTION, OPEN_TASKS],
      sortProperty: PRIORITY,
      sortDirection: "ASC",
    },
    {
      name: "Next actions",
      folder: settings.projectsFolder,
      extraFilters: [`${NEXT_DUE} != null`],
      order: [FILE_FOLDER, FILE_NAME, NEXT_ACTION, NEXT_DUE, PRIORITY],
      sortProperty: NEXT_DUE,
      sortDirection: "ASC",
    },
    {
      name: "Waiting",
      folder: settings.waitingProjectsFolder,
      extraFilters: [],
      order: [FILE_FOLDER, FILE_NAME, PRIORITY, WAITING_SINCE, NEXT_ACTION],
      sortProperty: WAITING_SINCE,
      sortDirection: "ASC",
    },
    {
      name: "Someday-Maybe review",
      folder: settings.somedayMaybeProjectsFolder,
      extraFilters: [],
      order: [FILE_FOLDER, FILE_NAME, PRIORITY, REVIEWED, NEXT_ACTION],
      sortProperty: REVIEWED,
      sortDirection: "ASC",
    },
    {
      name: "Scheduled",
      folder: settings.scheduledProjectsFolder,
      extraFilters: [],
      order: [FILE_FOLDER, FILE_NAME, NEXT_DUE, PRIORITY, NEXT_ACTION],
      sortProperty: NEXT_DUE,
      sortDirection: "ASC",
    },
  ];
}

function renderView(view: BaseViewSpec): string[] {
  const filters = buildFilterExpressions(view);
  const lines: string[] = [
    `  - type: table`,
    `    name: "${escapeYamlString(view.name)}"`,
  ];

  if (filters.length === 1) {
    lines.push(`    filters: ${filters[0]}`);
  } else if (filters.length > 1) {
    lines.push(`    filters:`, `      and:`);
    for (const filter of filters) {
      lines.push(`        - ${filter}`);
    }
  }

  lines.push(`    order:`);
  for (const column of view.order) {
    lines.push(`      - ${column}`);
  }

  lines.push(
    `    sort:`,
    `      - property: ${view.sortProperty}`,
    `        direction: ${view.sortDirection}`,
  );

  return lines;
}

function buildFilterExpressions(view: BaseViewSpec): string[] {
  const filters: string[] = [];
  if (view.folder.trim() !== "") {
    filters.push(`file.inFolder("${escapeYamlString(view.folder)}")`);
  }
  filters.push(...view.extraFilters);
  return filters;
}

function escapeYamlString(value: string): string {
  return value.replace(/"/g, '\\"');
}
