/**
 * Purpose:
 * - build the YAML content for a generated Obsidian Bases (.base) file.
 *
 * Responsibilities:
 * - wires up table views over the configured project folders, combining plugin-owned
 *   frontmatter fields (status, priority, waiting-since, reviewed) with the derived
 *   fields mirrored by derived-frontmatter.ts (next-due, next-action, open-tasks)
 *
 * Dependencies:
 * - settings-utils.ts (TaskManagerSettings) only
 *
 * Side Effects:
 * - none (pure string builder; the I/O — existence check, overwrite confirm, vault
 *   write — lives in main.ts, following the pattern of createProjectFile()/runQuickCapture())
 *
 * Notes:
 * - The .base YAML schema (https://obsidian.md/help/bases/syntax, /bases/functions) was
 *   cross-checked when this module was written, and confirmed against a live, Bases-UI-
 *   edited file afterward: `views`/`filters` structure, and/or/not filter grouping,
 *   `file.inFolder()`, `note.field` / `note["hyphenated-field"]` property access, the
 *   per-view `sort:` key (a list of `{property, direction}`), and bracket-notation
 *   property paths in `order:` are all genuinely honored by Bases — Bases' own UI
 *   round-trips them unchanged and even adds its own `sort:` entries on bracket-notation
 *   properties when the user sorts by clicking a column header.
 * - What bracket-notation properties DON'T get for free is a readable column header —
 *   with no override, Bases displays the raw `note["next-action"]`-style expression as
 *   the header text. `properties:` displayName overrides (below) fix that; still no
 *   `formulas:` block, which stays genuinely cosmetic/optional. If a view fails to
 *   render, Bases shows a visible error banner scoped to this one generated file;
 *   nothing else in the plugin depends on it parsing correctly.
 */
import { TaskManagerSettings } from "../settings/settings-utils";

type SortDirection = "ASC" | "DESC";

type BaseViewSpec = {
  name: string;
  /** Folder this view is scoped to; omitted from the filter entirely if blank. */
  folder: string;
  /** Additional filter expressions, ANDed with the folder filter. */
  extraFilters: string[];
  /** Column property paths, in display order. */
  order: string[];
  sortProperty: string;
  sortDirection: SortDirection;
};

const NEXT_DUE = 'note["next-due"]';
const NEXT_ACTION = 'note["next-action"]';
const OPEN_TASKS = 'note["open-tasks"]';
const WAITING_SINCE = 'note["waiting-since"]';
const FILE_NAME = "file.name";
const STATUS = "note.status";
const PRIORITY = "note.priority";
const REVIEWED = "note.reviewed";

/**
 * Bracket-notation properties render with no friendly header by default — Bases just
 * shows the raw expression (e.g. `note["next-action"]`) as the column title. Bare
 * dotted properties (priority, status, reviewed, file.name) already read fine and don't
 * need an entry here.
 */
const DISPLAY_NAMES: Record<string, string> = {
  [NEXT_DUE]: "Next due",
  [NEXT_ACTION]: "Next action",
  [OPEN_TASKS]: "Open tasks",
  [WAITING_SINCE]: "Waiting since",
};

export function buildTaskBaseFileContent(settings: TaskManagerSettings): string {
  const views = buildViewSpecs(settings);
  const lines: string[] = [
    "# Generated by the Task Manager plugin's \"Create Task Bases\" command.",
    "# Safe to edit freely from here on — re-running the command will ask before overwriting.",
    "views:",
  ];

  for (const view of views) {
    lines.push(...renderView(view));
  }

  lines.push("properties:", ...renderDisplayNames());

  return `${lines.join("\n")}\n`;
}

function renderDisplayNames(): string[] {
  const lines: string[] = [];
  for (const [property, displayName] of Object.entries(DISPLAY_NAMES)) {
    lines.push(`  ${property}:`, `    displayName: "${escapeYamlString(displayName)}"`);
  }
  return lines;
}

function buildViewSpecs(settings: TaskManagerSettings): BaseViewSpec[] {
  return [
    {
      name: "Active projects",
      folder: settings.projectsFolder,
      extraFilters: [`${STATUS} == "todo"`],
      order: [FILE_NAME, PRIORITY, NEXT_DUE, NEXT_ACTION, OPEN_TASKS],
      sortProperty: PRIORITY,
      sortDirection: "ASC",
    },
    {
      name: "Next actions",
      folder: settings.projectsFolder,
      extraFilters: [`${NEXT_DUE} != null`],
      order: [FILE_NAME, NEXT_ACTION, NEXT_DUE, PRIORITY],
      sortProperty: NEXT_DUE,
      sortDirection: "ASC",
    },
    {
      name: "Waiting",
      folder: settings.waitingProjectsFolder,
      extraFilters: [],
      order: [FILE_NAME, PRIORITY, WAITING_SINCE, NEXT_ACTION],
      sortProperty: WAITING_SINCE,
      sortDirection: "ASC",
    },
    {
      name: "Someday-Maybe review",
      folder: settings.somedayMaybeProjectsFolder,
      extraFilters: [],
      order: [FILE_NAME, PRIORITY, REVIEWED, NEXT_ACTION],
      sortProperty: REVIEWED,
      sortDirection: "ASC",
    },
    {
      name: "Scheduled",
      folder: settings.scheduledProjectsFolder,
      extraFilters: [],
      order: [FILE_NAME, NEXT_DUE, PRIORITY, NEXT_ACTION],
      sortProperty: NEXT_DUE,
      sortDirection: "ASC",
    },
  ];
}

function renderView(view: BaseViewSpec): string[] {
  const filters = buildFilterExpressions(view);
  const lines: string[] = [
    `  - type: table`,
    `    name: "${escapeYamlString(view.name)}"`,
  ];

  if (filters.length === 1) {
    lines.push(`    filters: ${filters[0]}`);
  } else if (filters.length > 1) {
    lines.push(`    filters:`, `      and:`);
    for (const filter of filters) {
      lines.push(`        - ${filter}`);
    }
  }

  lines.push(`    order:`);
  for (const column of view.order) {
    lines.push(`      - ${column}`);
  }

  lines.push(
    `    sort:`,
    `      - property: ${view.sortProperty}`,
    `        direction: ${view.sortDirection}`,
  );

  return lines;
}

function buildFilterExpressions(view: BaseViewSpec): string[] {
  const filters: string[] = [];
  if (view.folder.trim() !== "") {
    filters.push(`file.inFolder("${escapeYamlString(view.folder)}")`);
  }
  filters.push(...view.extraFilters);
  return filters;
}

function escapeYamlString(value: string): string {
  return value.replace(/"/g, '\\"');
}
