/**
 * Purpose:
 * - pure JSON Canvas (https://jsoncanvas.org/spec/1.0/) model for the Task Board.
 *
 * Responsibilities:
 * - lays out one group ("column") per status and one file node ("card") per project
 * - parses/serializes canvas JSON, tolerant of malformed input
 * - determines which group a card's node currently sits in (geometric containment —
 *   JSON Canvas has no explicit node/group membership field)
 * - diffs a canvas's card placement against known project statuses
 *
 * Dependencies:
 * - none outside language/runtime primitives
 *
 * Side Effects:
 * - none (pure)
 *
 * Notes:
 * - Every plugin-managed node/group id is prefixed with MANAGED_NODE_PREFIX and is
 *   otherwise deterministic (a hash of the file path for cards, the status name for
 *   groups) — regenerating with unchanged input reproduces byte-identical ids, which
 *   keeps unrelated re-layouts from looking like node churn to Obsidian Sync, and makes
 *   "is this node ours?" a plain prefix test. Any node/edge whose id lacks the prefix is
 *   user content and is always carried forward untouched by buildBoardData().
 */

export const MANAGED_NODE_PREFIX = "tm-";

export type StatusColumn = {
  status: string;
  label: string;
};

/** Column order left-to-right. No "completed" column — that list is unbounded. */
export const STATUS_COLUMNS: StatusColumn[] = [
  { status: "todo", label: "Active" },
  { status: "waiting", label: "Waiting" },
  { status: "someday-maybe", label: "Someday-Maybe" },
  { status: "scheduled", label: "Scheduled" },
];

export type BoardProject = {
  path: string;
  status: string;
  priority: number;
  basename: string;
};

type CanvasNodeCommon = {
  id: string;
  x: number;
  y: number;
  width: number;
  height: number;
};

export type CanvasFileNode = CanvasNodeCommon & {
  type: "file";
  file: string;
};

export type CanvasGroupNode = CanvasNodeCommon & {
  type: "group";
  label?: string;
};

/** Any node type this module doesn't generate (text/link/group-without-our-prefix/etc.) is passed through opaquely. */
export type CanvasOtherNode = CanvasNodeCommon & {
  type: string;
  [key: string]: unknown;
};

export type CanvasNode = CanvasFileNode | CanvasGroupNode | CanvasOtherNode;

export type CanvasEdge = {
  id: string;
  fromNode: string;
  toNode: string;
  [key: string]: unknown;
};

export type CanvasData = {
  nodes: CanvasNode[];
  edges: CanvasEdge[];
};

const PADDING = 20;
const HEADER_HEIGHT = 60;
const CARD_WIDTH = 400;
const CARD_HEIGHT = 140;
const CARD_GUTTER = 20;
const GROUP_WIDTH = CARD_WIDTH + PADDING * 2;
const COLUMN_SPACING = GROUP_WIDTH + 40;
const MIN_GROUP_HEIGHT = 600;

export function isManagedId(id: string): boolean {
  return id.startsWith(MANAGED_NODE_PREFIX);
}

function isFileNode(node: CanvasNode): node is CanvasFileNode {
  return node.type === "file";
}

function isGroupNode(node: CanvasNode): node is CanvasGroupNode {
  return node.type === "group";
}

function groupNodeId(status: string): string {
  return `${MANAGED_NODE_PREFIX}group-${status}`;
}

function fileNodeId(path: string): string {
  return `${MANAGED_NODE_PREFIX}file-${hashPath(path)}`;
}

/** djb2 — deterministic, good enough to keep card ids stable and collision-unlikely for a single vault's file count. */
function hashPath(path: string): string {
  let hash = 5381;
  for (let index = 0; index < path.length; index += 1) {
    hash = ((hash << 5) + hash + path.charCodeAt(index)) >>> 0;
  }
  return hash.toString(36);
}

/**
 * Rebuilds every plugin-managed group/card from `projects`, laid out column-by-column,
 * cards stacked by priority ascending then basename. All non-managed nodes/edges from
 * `existing` (user sticky notes, other file references, manually drawn edges) are kept
 * verbatim. Edges are never generated by this module and are always carried forward as-is
 * — group/card membership is purely geometric, so there's nothing for an edge to encode.
 */
export function buildBoardData(projects: BoardProject[], existing: CanvasData | null): CanvasData {
  const preservedNodes = (existing?.nodes ?? []).filter((node) => !isManagedId(node.id));
  const preservedEdges = existing?.edges ?? [];

  const managedNodes: CanvasNode[] = [];

  STATUS_COLUMNS.forEach((column, columnIndex) => {
    const columnProjects = projects
      .filter((project) => project.status === column.status)
      .sort((left, right) => left.priority - right.priority || left.basename.localeCompare(right.basename));

    const groupX = columnIndex * COLUMN_SPACING;
    const groupHeight = Math.max(
      MIN_GROUP_HEIGHT,
      HEADER_HEIGHT + columnProjects.length * (CARD_HEIGHT + CARD_GUTTER) + PADDING,
    );

    managedNodes.push({
      id: groupNodeId(column.status),
      type: "group",
      label: column.label,
      x: groupX,
      y: 0,
      width: GROUP_WIDTH,
      height: groupHeight,
    });

    columnProjects.forEach((project, cardIndex) => {
      managedNodes.push({
        id: fileNodeId(project.path),
        type: "file",
        file: project.path,
        x: groupX + PADDING,
        y: HEADER_HEIGHT + cardIndex * (CARD_HEIGHT + CARD_GUTTER),
        width: CARD_WIDTH,
        height: CARD_HEIGHT,
      });
    });
  });

  return {
    nodes: [...preservedNodes, ...managedNodes],
    edges: preservedEdges,
  };
}

export function parseCanvas(json: string): CanvasData | null {
  try {
    const parsed = JSON.parse(json);
    if (!parsed || typeof parsed !== "object") {
      return null;
    }

    const nodes = Array.isArray(parsed.nodes) ? parsed.nodes : [];
    const edges = Array.isArray(parsed.edges) ? parsed.edges : [];
    return { nodes, edges };
  } catch {
    return null;
  }
}

export function serializeCanvas(data: CanvasData): string {
  return `${JSON.stringify(data, null, "\t")}\n`;
}

/**
 * The status implied by whichever managed group's bounding box contains the node's
 * center point, or null if the node sits outside every group (dragged to empty canvas
 * space) or inside more than zero but the match is ambiguous — first match wins, which
 * only matters if groups were manually resized to overlap.
 */
export function findNodeGroupStatus(node: CanvasFileNode, groups: CanvasGroupNode[]): string | null {
  const centerX = node.x + node.width / 2;
  const centerY = node.y + node.height / 2;

  for (const group of groups) {
    const withinX = centerX >= group.x && centerX <= group.x + group.width;
    const withinY = centerY >= group.y && centerY <= group.y + group.height;
    if (withinX && withinY && isManagedId(group.id) && group.id.startsWith(`${MANAGED_NODE_PREFIX}group-`)) {
      return group.id.slice(`${MANAGED_NODE_PREFIX}group-`.length);
    }
  }

  return null;
}

export type BoardStatusChange = {
  path: string;
  newStatus: string;
};

export type BoardDiffResult = {
  changes: BoardStatusChange[];
  /** Vault paths that appear on more than one managed card — ambiguous, so skipped entirely. */
  duplicatePaths: string[];
};

/**
 * Compares each managed card's current group against `statusByPath` (the project's
 * actual status on disk). A card with no known status (file renamed/deleted out from
 * under it) or sitting outside every group is silently skipped — it self-heals on the
 * next regenerate rather than producing a spurious status write.
 */
export function diffBoardStatuses(data: CanvasData, statusByPath: Map<string, string>): BoardDiffResult {
  const groups = data.nodes.filter(isGroupNode);
  const managedFileNodesByPath = new Map<string, CanvasFileNode[]>();

  for (const node of data.nodes) {
    if (!isFileNode(node) || !isManagedId(node.id)) {
      continue;
    }

    const existingList = managedFileNodesByPath.get(node.file) ?? [];
    existingList.push(node);
    managedFileNodesByPath.set(node.file, existingList);
  }

  const changes: BoardStatusChange[] = [];
  const duplicatePaths: string[] = [];

  for (const [path, nodes] of managedFileNodesByPath) {
    if (nodes.length > 1) {
      duplicatePaths.push(path);
      continue;
    }

    const currentStatus = statusByPath.get(path);
    if (currentStatus === undefined) {
      continue;
    }

    const groupStatus = findNodeGroupStatus(nodes[0], groups);
    if (groupStatus === null || groupStatus === currentStatus) {
      continue;
    }

    changes.push({ path, newStatus: groupStatus });
  }

  return { changes, duplicatePaths };
}
